# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
   
  build:
    
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Init terraform
        working-directory: ./terraform_deploy
        run: terraform init
        
      - name: Terraform plan
        working-directory: ./terraform_deploy
        run: terraform plan -no-color
        continue-on-error: true
        env:
          TF_VAR_credentials: ${{secrets.TF_VAR_CREDENTIALS}} 
      
      - name: Terraform apply 
        working-directory: ./terraform_deploy
        run: terraform apply -auto-approve
        continue-on-error: true
        env:
          TF_VAR_credentials: ${{secrets.TF_VAR_CREDENTIALS}} 
        
